{{- if and (not .Values.mqtt.existingSecret) (or .Values.mqtt.username .Values.mqtt.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wled-mcp.fullname" . }}-mqtt
  labels: {{- include "wled-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mqtt.username | quote }}
  password: {{ .Values.mqtt.password | quote }}
{{- end }}
